### ISSUE TITLE
Add dark scrollbar

### ISSUE THREAD

**Issue by muznyo** [ente-io/bhari-frame#78]
Ente has dark mode focused ui, but it has light scrollbar, which makes user experience worse

![image](https://user-images.githubusercontent.com/24987471/192119040-d8ed8123-f1f7-4876-8137-694999e07d05.png)

please add dark scrollbars

**Comment by abhinavkgrd** [comment]
Hii @muznyo, Thank you for reporting this 😄 ... This should be a quick fix... I will try to get it fixed soon and include it in the release.

**Comment by muznyo** [comment]
Looks like it's fixed! Closing.
